### ISSUE TITLE
Signature does not match when S3 object has special symbols in path

### ISSUE THREAD

**Issue by nickcaballero** [grafana/k6-jslib-aws#78]
Calling `getObject` or `listObjects` on the S3 client with a URL that has a `=` in the path fails. According to diagram from [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html), the URI should also be encoded, except for forward slashes.

![diagram](https://docs.aws.amazon.com/images/AmazonS3/latest/API/images/sigV4-using-auth-header.png)

Using folder structures like `bucket/state=fl/city=orlando/data.json` is fairly common.

**Comment by nickcaballero** [comment]
I have a commit with changes that seems to fix it, but we may want to rename the `uriEscapePath` to something else since it's a bit of a misnomer.

https://github.com/grafana/k6-jslib-aws/commit/c594d1a8fb961cd2d2e11e245dfc1913b5e75de4#diff-03fbd3803705ec566e6a805abe90ff0f2ede38e2f040f05357cc96e2d7165008

**Comment by oleiade** [comment]
Hey @nickcaballero, I believe this is fixed by version `v0.12.3` where we explicitly addressed the URI encoding/double encoding scenarios involving spaces and special characters.

I will close this as a result, but please feel free to take it for a spin, and if you still find breaking use cases, let us know, and we'll reopen it 🙇🏻
